[build-system]
requires = ["flit_core >=3.2,<4"]
build-backend = "flit_core.buildapi"

[project]
authors = [{name = "Tom Deakin", email = "tom.deakin@bristol.ac.uk"}]
dynamic = ["version", "description"]
